# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - name: Installing poetry
        run: |
          export $( \
              PYTHONFAULTHANDLER=TRUE \
              PYTHONUNBUFFERED=TRUE \
              PIP_DISABLE_PIP_VERSION_CHECK=on \
              PIP_NO_CACHE_DIR=off \
          )
          pip install --upgrade pip \
          && pip install "poetry==1.0.5"
  check-core:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Installing dependencies
        run: make install
        working-directory: ./core
      - name: Linting
        run: make lint
        working-directory: ./core
      - name: Unit testing
        run: make test
        working-directory: ./core
  check-action-server:
    runs-on: ubuntu-latest
    needs: setup
    env:
      working-directory: ./action-server
    steps:
      - name: Installing dependencies
        run: make install
        working-directory: ${{env.working-directory}}
      - name: Linting
        run: make lint
        working-directory: ${{env.working-directory}}
      - name: Unit testing
        run: make test
        working-directory: ${{env.working-directory}}
